name = "manta-weather"
main = "src/worker/index.ts"
compatibility_date = "2024-01-01"

[durable_objects]
bindings = [
  { name = "WEATHER_DO", class_name = "WeatherDO" }
]

[[migrations]]
tag = "v1"
new_classes = ["WeatherDO"]